export enum BaseActionTypes {
    BASE_CHANGE_FILTER_DRAWER_STATUS = "BASE_CHANGE_FILTER_DRAWER_STATUS",
    BASE_CHANGE_BASKET_DRAWER_STATUS = "BASE_CHANGE_BASKET_DRAWER_STATUS",
    BASE_INITIALIZE_DATA = "BASE_INITIALIZE_DATA",
    BASE_SET_PRODUCTS = "BASE_SET_PRODUCTS",
    BASE_SET_BASKET = "BASE_SET_BASKET"
} 